version: '3'

services: 
  go-backend:
#    build: ./go
    image: intento
#    volumes: 
#      - ./product:/usr/src/app
    ports:
     - "4000:4000"
  vue-frontend:
    image: intento2
#    build: 
#    volumes: 
#      - ./asdjfhk
    ports:
      - "4001:4001"
    depends_on: 
      - go-backend
web:
  environment:
    - PORT=4001

