version: '3.8'

services: 
  go-backend:
    image: mpgarciav/vuego-demoapp:backend
    ports:
     - "4001:4001"    
    
  vue-frontend:
    image: mpgarciav/vuego-demoapp:frontend
    ports:
      - "4000:80"
    depends_on: 
      - go-backend
    environment:
      - VUE_APP_API_ENDPOINT=http://go-backend:4001/api
